CREATE TABLE `DEVELOPERMANAGER`.`DEVELOPERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(250) NOT NULL,
  `SKILL` VARCHAR(250) NOT NULL,
  `SALARY` INT NOT NULL,
  `EXPERIENCE` INT NOT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `DEVELOPERMANAGER`.`PROJECTS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `DEVELOPERMANAGER`.`PROJECTS_DEVELOPERS` (
  `projectID` BIGINT NOT NULL,
  `developerID` BIGINT NOT NULL);

use projects;
INSERT INTO DEVELOPERMANAGER.PROJECTS (ID, NAME)
                               VALUES ('1', 'PRoject_1');
INSERT INTO DEVELOPERMANAGER.PROJECTS (ID, NAME)
                               VALUES ('2', 'PRoject_2');
INSERT INTO DEVELOPERMANAGER.PROJECTS (ID, NAME)
                               VALUES ('3', 'PRoject_3');