CREATE TABLE `DEVELOPERMANAGER`.`DEVELOPERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(250) NOT NULL,
  `SKILL` VARCHAR(250) NOT NULL,
  `SALARY` INT NOT NULL,
  `EXPERIENCE` INT NOT NULL,
  PRIMARY KEY (`ID`));