INSERT INTO DEVELOPERMANAGER.DEVELOPERS (ID, NAME, SKILL, SALARY, EXPERIENCE)
                                 VALUES ('1', 'Dev1', 'JAVA', '3000', '1');
INSERT INTO DEVELOPERMANAGER.DEVELOPERS (ID, NAME, SKILL, SALARY, EXPERIENCE)
                                 VALUES ('2', 'Dev2', 'C++', '1200', '2');
INSERT INTO DEVELOPERMANAGER.DEVELOPERS (ID, NAME, SKILL, SALARY, EXPERIENCE)
                                 VALUES ('3', 'Dev3', 'C#', '3200', '3');
INSERT INTO DEVELOPERMANAGER.DEVELOPERS (ID, NAME, SKILL, SALARY, EXPERIENCE)
                                 VALUES ('4', 'Dev4', 'JS', '4300', '4');
INSERT INTO DEVELOPERMANAGER.DEVELOPERS (ID, NAME, SKILL, SALARY, EXPERIENCE)
                                 VALUES ('5', 'Dev5', 'HTML', '1000', '5');

INSERT INTO DEVELOPERMANAGER.PROJECTS (ID, NAME)
                               VALUES ('1', 'PRoject_1');
INSERT INTO DEVELOPERMANAGER.PROJECTS (ID, NAME)
                               VALUES ('2', 'PRoject_2');
INSERT INTO DEVELOPERMANAGER.PROJECTS (ID, NAME)
                               VALUES ('3', 'PRoject_3');